spring:
  datasource:
    url: jdbc:h2:mem:career_planning_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: none    # 修改为 none，使用 SQL 脚本初始化
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

server:
  port: 8080

# JWT 配置
jwt:
  access-token-expiration: 3600000  # 1小时 (毫秒)
  refresh-token-expiration: 604800000  # 7天 (毫秒)

# 日志配置
logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR
    com.university.careerplanning: DEBUG

# 跨域配置
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

# 应用程序特定配置
app:
  security:
    jwt-secret: career_planning_secret_key_for_development_only

qianwen:
  api:
    key: sk-6ceb7795be7c4dcc83ed8b1918e8a550
    url: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation