spring:
  application:
    name: career-planning-platform

server:
  port: 8080
  servlet:
    context-path: /

# 通义千问API配置
qianwen:
  api:
    url: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
    key: ${QIANWEN_API_KEY:your_default_key_for_development} # 请使用环境变量配置
  model:
    name: qwen-plus # 或使用其他可用模型

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  allowed-headers: "*"

# 日志配置
logging:
  level:
    root: INFO
    com.university.careerplanning: DEBUG
